let inputWidth;
let inputHeight;
inputWidth = prompt("Nhap vao chieu rong");
inputHeight = prompt("Nhap vao chieu cao");
let width = parseInt(inputWidth);
let height = parseInt(inputHeight);
let area = width * height;
alert("Dien tich cua hinh la: " + area);
document.write('Chieu rong cua hinh la: ' + width);
document.write('Chieu cao cua hinh la: ' + height);
document.write('Dien tich cua hinh la: ' + area);
